name: Scala CLI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17' # Scala CLI の推奨 Java バージョン

      - name: Cache Coursier
        uses: coursier/cache-action@v6

      - name: Setup Scala CLI
        uses: VirtusLab/scala-cli-setup@main
        with:
          scala-version: "3.3.x" # 使用する Scala のバージョン (例: 3.3.x)

      - name: Compile
        run: scala-cli compile .

      # 3. Scala CLI を使ってコードを実行します
      - name: Run Scala script
        run: scala-cli run Products.scala

      - name: Test
        run: scala-cli test .